# This is a basic workflow that is manually triggered

name: Upload Media to Instagram

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  # schedule:
    # Run this workflow daily at midnight
    # - cron: "0 5 * * *"

    
jobs:
  upload-media:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        PIP install Pillow

    - name: Run the Python script
      env:
        FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
        FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
      run: |
        python InstaQuotes/upload_image.py

